-- 코드를 입력하세요
SELECT b.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, SUM(PRICE*SALES) as TOTAL_SALES
FROM BOOK as a JOIN AUTHOR as b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES as c ON a.BOOK_ID=c.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 and MONTH(SALES_DATE)=1
GROUP BY b.AUTHOR_ID, a.CATEGORY
ORDER BY b.AUTHOR_ID,a.CATEGORY DESC