-- 코드를 입력하세요
WITH TEMP AS(
    SELECT s.BOOK_ID,CATEGORY,AUTHOR_ID,DATE_FORMAT(SALES_DATE,
"%Y-%m-%d"),PRICE*SALES as TOTAL_SALES
    FROM BOOK_SALES as s
    JOIN BOOK as b
    ON s.BOOK_ID=b.BOOK_ID   
    WHERE YEAR(SALES_DATE)=2022 and MONTH(SALES_DATE)=1
)

SELECT t.AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(TOTAL_SALES) as TOTAL_SALES
FROM TEMP as t
JOIN AUTHOR as a
ON t.AUTHOR_ID=a.AUTHOR_ID
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY t.AUTHOR_ID, CATEGORY DESC