-- 코드를 작성해주세요
WITH CC AS (
    SELECT PARENT_ID, COUNT(*) as CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
),
ED AS (
    SELECT ID
    FROM ECOLI_DATA
)

SELECT ED.ID, IFNULL(CC.CHILD_COUNT,0) as CHILD_COUNT
FROM ED as ED
LEFT JOIN CC as CC
    ON ED.ID = CC.PARENT_ID
ORDER BY ID 
    
