-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID,USER_ID,SUM(SALES_AMOUNT) as SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE)=2022 and MONTH(SALES_DATE)=3
GROUP BY SALES_DATE,PRODUCT_ID,USER_ID
UNION
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
       PRODUCT_ID,
       NULL AS USER_ID,
       SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
GROUP BY SALES_DATE, PRODUCT_ID

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID