-- 코드를 작성해주세요
WITH TEMP_TABLE AS (
    SELECT 
        ID,
        NTILE(4) OVER (
            ORDER BY SIZE_OF_COLONY
        ) AS N
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE 
        WHEN N=1 THEN "LOW"
        WHEN N=2 THEN "MEDIUM"
        WHEN N=3 THEN "HIGH"
        WHEN N=4 THEN "CRITICAL"
    END AS COLONY_NAME
FROM TEMP_TABLE
ORDER BY ID