SELECT A.ID, CASE 
WHEN TILE=1 THEN "LOW"
WHEN TILE=2 THEN "MEDIUM"
WHEN TILE=3 THEN "HIGH"
WHEN TILE=4 THEN "CRITICAL"
END AS COLONY_NAME
FROM ECOLI_DATA AS A JOIN (SELECT ID,
    NTILE(4) OVER(
        ORDER BY SIZE_OF_COLONY
    ) AS TILE
FROM ECOLI_DATA) AS B ON A.ID=B.ID