-- 코드를 입력하세요
SELECT a.REST_ID as REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO as a JOIN REST_REVIEW as b
ON a.REST_ID = b.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY a.REST_ID 
ORDER BY SCORE DESC,FAVORITES DESC;