-- 코드를 입력하세요
WITH TEMP_TABLE AS (
    SELECT O.USER_ID, GENDER, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE AS O
    JOIN USER_INFO AS U
    ON O.USER_ID = U.USER_ID
    WHERE GENDER IS NOT NULL
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), O.USER_ID
)

SELECT YEAR, MONTH, GENDER, COUNT(USER_ID) AS USERS
FROM TEMP_TABLE
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER