SELECT a.CAR_ID, CASE
        WHEN START_DATE is null THEN "대여 가능"
		ELSE "대여중"
END AS AVAILABILITY
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) AS a
LEFT JOIN (
    SELECT CAR_ID, START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16'
      AND END_DATE   >= '2022-10-16'
    GROUP BY CAR_ID
) AS b
ON a.CAR_ID = b.CAR_ID
ORDER BY CAR_ID DESC;
