-- 코드를 입력하세요
WITH TEMP_TABLE1 AS (
    SELECT 
        CAR_ID, "대여중" AS AVAILABILITY
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE<="2022-10-16" AND END_DATE>="2022-10-16"
),
TEMP_TABLE2 AS (
    SELECT 
        DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT B.CAR_ID, IFNULL(AVAILABILITY, "대여 가능") AS AVAILABILITY
FROM 
    TEMP_TABLE1 AS A RIGHT JOIN TEMP_TABLE2 AS B
    ON A.CAR_ID=B.CAR_ID
ORDER BY CAR_ID DESC