-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH,CAR_ID,COUNT(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)=2022 and (8<=MONTH(START_DATE) and MONTH(START_DATE)<=10)
GROUP BY CAR_ID
HAVING COUNT(HISTORY_ID)>=5) and YEAR(START_DATE)=2022 and (8<=MONTH(START_DATE) and MONTH(START_DATE)<=10)
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH, CAR_ID DESC
