-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM BOOK as a JOIN BOOK_SALES as b ON
a.BOOK_ID=b.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 and MONTH(SALES_DATE)=1
GROUP BY CATEGORY
ORDER BY CATEGORY