-- 코드를 입력하세요
WITH TEMP_TABLE AS (
    SELECT 
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        PRICE,
        RANK() OVER(
            PARTITION BY CATEGORY
            ORDER BY PRICE DESC    
        ) AS R
    FROM 
        FOOD_PRODUCT
    WHERE 
        CATEGORY="과자" OR CATEGORY="국" OR CATEGORY="김치" OR CATEGORY="식용유"
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM TEMP_TABLE
WHERE R=1
ORDER BY MAX_PRICE DESC